### ISSUE TITLE
add_short_metadata not saved when using write_output()

### ISSUE THREAD

**Issue by neaptide** [teresaupdyke/qccodar#14]
The additional metadata added for QCD (r.metadata['QCD']) in the Radial object is generated by add_short_metadata, but not being saved with write_output().  Suspect a bug in HFRadarPy not recognizing it.  I'm using the version of HFRadarPy from pip install (PyPi) not his latest github version.

**Comment by teresaupdyke** [comment]
The latest rucool/HFRadarPy Github version solves this issue.
